.\" $Id$ -*-nroff-*-
.TH "lwhich" 1 "2017-02-18"

.SH 名前
lwhich \- コマンドの場所

.SH 書式
.B lwhich [-aslrb] program ...

.SH 説明
.PP
\fBlwhich\fR は、引数を、現在の環境で実行されるパス名で表示します。
.br
引数の名前に一致する実行ファイルは PATH 環境変数から検索します。
.br
\fB\-l\fR / \fB-r\fR オプションを指定しない場合、シンボリック・リンクは追跡しません。


.SH オプション

.TP
.BI \-a
各引数に一致したすべてのパス名を表示します。
.TP
.BI \-s
パス名等を表示せず、戻り値のみセットします。
.TP
.BI \-l
シンボリック・リンクの場合、\fB\->\fR の後にリンク情報を表示します。
.br
(\fBls -l\fR と同様)
.TP
.BI \-r
シンボリック・リンクの場合、\fB\->\fR の後にリンク先の最終フルパス情報を表示します。
.TP
.BI \-d
最終更新日時を「yyyy-mm-dd hh:mm:ss」形式で表示します。
.br
日時はローカルです。
.br
ロケールは使っていません。必ずこの形式で出力します。
.br
リンクの場合、リンク先の日時になるので、ls で表示されるものと異なります。
.TP
.BI \-b
サイズをバイト単位で表示します。
.br
リンクの場合、リンク先のバイト数になるので、ls で表示されるものと異なります。

.SH 終了ステータス

.TP
.BI 0
引数に指定したコマンドがすべて見つかり、実行可能な場合
.TP
.BI 1
いくつかのコマンドがないか、実行可能でない場合
.TP
.BI 2
ひとつもコマンドがないか、実行可能でない場合
.TP
.BI 3
無効なオプションを指定した場合
.TP
.BI 4
何らかのエラーが起きた場合


.SH 作者
Takataka.
